### IMPORT

In [2]:
import numpy as np

### NUMPY ARRAYS

In [4]:
# Create the numpy array
mylist = [1,2,3]
print(mylist)
print(type(mylist))

[1, 2, 3]
<class 'list'>


In [7]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]
print(mylist)
np.array(mylist)

# We can count the number of dimensions of the array by counting the amount of brackets from outside to inside. In this case, there are two brackets, so this is a 2D array.
# We can also use the ndim attribute to check the number of dimensions.

arr = np.array(mylist)
print(arr.ndim)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2


In [8]:
# Shape of the array
print(arr.shape)
# It means that each dimension has 3 elements.
# We have two dimensions.

(3, 3)


In [ ]:
np.arange(0,10,2)
# It creates an array from 0 to 10 with a step of 2.

array([0, 2, 4, 6, 8])

In [13]:
print(np.zeros(5))
# It creates an array with five zero elements.
print(np.ones((3,4))) # It is similar to the shape attribute.

[0. 0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# IMPORTANT: Numpy can add, subtract, multiply, and divide arrays of the same shape ELEMENT WISE.
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Before addition:\n{a}")
print(f"After addition:\n{a+10}")

# But we can not do the same thing with lists

Before addition:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
After addition:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [17]:
# LINSPACE
print(np.linspace(0,100,20))

# It creates the 20 numbers between 0 and 100 equally spaced.
print(len(np.linspace(0,100,20)))

[  0.           5.26315789  10.52631579  15.78947368  21.05263158
  26.31578947  31.57894737  36.84210526  42.10526316  47.36842105
  52.63157895  57.89473684  63.15789474  68.42105263  73.68421053
  78.94736842  84.21052632  89.47368421  94.73684211 100.        ]
20


In [ ]:
# DIAGONAL
np.eye(5)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

### NUMPY ARRAY PART 2

In [ ]:
np.random.rand(4,4)
# Just get the random number between 0 and 1
# Always we can adjust the shape

array([[0.56749945, 0.67203767, 0.4003655 , 0.21593396],
       [0.50218177, 0.8168869 , 0.63443532, 0.37212991],
       [0.35183735, 0.81805673, 0.47247365, 0.47762438],
       [0.9922657 , 0.66499435, 0.59408091, 0.29295991]])

In [24]:
# Standard Normal Distribution
arr = np.random.randn(4,4)
print(arr.mean())
print(arr.std())
print(arr)

-0.1044044056821734
0.7985416958096552
[[ 0.6509155  -0.66310496 -0.75144546  0.51130613]
 [-0.42203782 -0.8882799  -0.6094613  -0.94601352]
 [-0.92617279  0.82917064  0.11539304  0.05458411]
 [ 0.7513469   0.9794647  -1.46359427  1.1074585 ]]


In [28]:
# Random integer numbers
print(np.random.randint(0,100))

68


In [ ]:
# IMPORTANT: SEED 42 --> JUST IN THE SAME CELL
SEED = 42
np.random.seed(SEED)
print(np.random.rand(4,4))

# They will not change every time we run the code. But if we change the seed number, the random numbers will change.

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]


In [42]:
# RESHAPE
SEED = 42
np.random.seed(SEED)

arr = np.random.randint(0,25,20)
print(arr)

print(arr.reshape(5,2,2))
# print(arr.reshape(1,25))
# print(arr.reshape(5,5))

[ 6 19 14 10  7 20  6 18 22 10 10 23 20  3  7 23  2 21 20  1]
[[[ 6 19]
  [14 10]]

 [[ 7 20]
  [ 6 18]]

 [[22 10]
  [10 23]]

 [[20  3]
  [ 7 23]]

 [[ 2 21]
  [20  1]]]


In [45]:
# STILL RESHAPE

arr = np.arange(1,13)
print(arr.reshape(3,2,2))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# MAX and MIN

arr = np.random.randint(0, 1200, 100)


arr = arr.reshape(2,2,5,5)
print(arr)
print(arr.max())
print(arr.min())
print(arr.argmax())  # it gives the index of the max value
print(arr.argmin())  # it gives the index of the min value

'''
Yes.
When you see an index like 90 from argmin() or argmax(), it means NumPy flattened the entire array into a 1D array and then counted positions linearly, ignoring the original dimensions.
'''

[[[[ 895  159  851  689  379]
   [ 956  690 1191 1066  284]
   [ 396   11  498  753   34]
   [ 726  848   89  775  604]
   [ 969 1021  417  114  616]]

  [[ 825 1098  412  728 1020]
   [ 760  675  456  919  191]
   [ 738 1122  977 1008   95]
   [ 662   36  278  216  866]
   [ 872   61  595  728  396]]]


 [[[ 698 1042  176  395  444]
   [  75  264  454  717  734]
   [ 850  143  884 1092 1122]
   [ 395 1048  947  890 1174]
   [1167  568 1062  108 1065]]

  [[ 934  397  633 1156 1186]
   [ 732  234  657  750  587]
   [1032 1097  953  491  912]
   [1197 1191  169  945  794]
   [ 633   28 1188  338  499]]]]
1197
11
90
11


In [51]:
# FLATEN
arr = arr.flatten()
arr

array([ 895,  159,  851,  689,  379,  956,  690, 1191, 1066,  284,  396,
         11,  498,  753,   34,  726,  848,   89,  775,  604,  969, 1021,
        417,  114,  616,  825, 1098,  412,  728, 1020,  760,  675,  456,
        919,  191,  738, 1122,  977, 1008,   95,  662,   36,  278,  216,
        866,  872,   61,  595,  728,  396,  698, 1042,  176,  395,  444,
         75,  264,  454,  717,  734,  850,  143,  884, 1092, 1122,  395,
       1048,  947,  890, 1174, 1167,  568, 1062,  108, 1065,  934,  397,
        633, 1156, 1186,  732,  234,  657,  750,  587, 1032, 1097,  953,
        491,  912, 1197, 1191,  169,  945,  794,  633,   28, 1188,  338,
        499])

### SLICING AND INDEXING

In [57]:
arr = np.arange(1,101)
print(arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [ ]:
arr[:-1] # It gives all the elements except the last one.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr[:5] # It gives the first five elements 0 - 4.

array([1, 2, 3, 4, 5])

In [ ]:
arr[5:] # It gives all the elements from index 5 to the end.

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39,
       40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56,
       57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
       91, 92, 93, 94, 95, 96, 97, 98, 99])

In [62]:
arr = np.arange(1,101)
arr = arr.reshape(10,10)
print(arr)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [60]:
arr[:][:] = 99
print(arr)

[[99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]
 [99 99 99 99 99 99 99 99 99 99]]


In [64]:
arr[:5][0].ndim

1

### CONDITION

In [65]:
arr = np.arange(1,12,1)

In [67]:
bool_arr = arr > 4

In [69]:
# DO THE FILTER
arr[bool_arr]

# Always return the true location

array([ 5,  6,  7,  8,  9, 10, 11])